### ISSUE TITLE
Octoshark::Error::NoCurrentConnection, sometimes?

### ISSUE THREAD

**Issue by thewatts** [dalibor/octoshark#38]
We're using Octoshark to hot-swap database connections, configured just like how the README specifies.

```ruby
class ApplicationRecord < ActiveRecord::Base
  def self.connection
    CONNECTION_MANAGER.current_connection
  end
end
```

And we have some background jobs that loop through our clients and call `with_connection` on the database itself.

```ruby
class DatabaseWorker < ApplicationWorker
  sidekiq_options queue: :default

  def perform(database_key)
    CONNECTION_MANAGER.with_connection(database_key) do
      # do stuff
    end
  end
end
```

And then a global job that queues all of the workers up per database:

```ruby
class GlobalWorker < ApplicationWorker
  sidekiq_options queue: :default

  def perform
    DATABASES_KEYS.each do |database_key|
      DatabaseWorker.peform_later(database_key)
    end
  end
end
```

For some reason - on occassion - when the global job is triggered - we get `Octoshark::Error::NoCurrentConnection` errors for ~ a quarter of the databases we're connecting to.

These databases are getting connected to via the web app's processes as well, could it be a pool size issue?
When we retry the jobs (from the dead queue in Sidekiq), they seemingly always work the second try.

Thanks for your help, and for this amazing little gem!

---

Edit: additional details:

We're using the Pools manager

```ruby
def self.connection_manager
  @connection_manager ||= Octoshark::ConnectionPoolsManager.new(pool_config)
end
```

**Comment by dalibor** [comment]
Hm, hard to tell, but it might be an issue with how `ConnectionPoolsManager` is initialized if that happens in Sidekiq multi-thread environment? I'm using both `ConnectionManager` and `ConnectionPoolsManager` without a problem.

I initialize the `ConnectionPoolsManager` object to a constant in an initializer (sample code below). If you initialize `ConnectionPoolsManager` dynamically during a job processing in a concurrent environment with multiple Sidekiq threads it could initialize more than one `ConnectionPoolsManager` that might cause the issue.

```ruby
# config/initializers/octoshark.rb
require 'active_record/database_configurations'

CONNECTION_MANAGER = Octoshark::ConnectionPoolsManager.new(
  DatabaseServer.all.each_with_object({}) { |ds, configs|
    configs[ds.id] = ds.config
  }
)
```

Alternatively, you could use a Mutex to lock the initialization of `Octoshark::ConnectionPoolsManager`, something like:

```ruby
def self.connection_manager
  @connection_manager ||= Mutex.new.synchronize do
    Octoshark::ConnectionPoolsManager.new(pool_config)
  end
end
```

Hope that helps.

**Comment by thewatts** [comment]
@dalibor thank you for your help!

So - instance variables, even from the context of a class method, are thread safe - which means that the different threads weren't sharing the same `ConnectionPoolsManager`.

We switched this to a constant and have since had no issues.

Thank you for your help! (and for this project!)

**Comment by dalibor** [comment]
@thewatts Awesome, great to hear!
